const categories = {
  defaultState: [
    {
      header: "Career",
      items: ["", "", "", ""],
    },
    {
      header: "Number of Children",
      items: ["", "", "", ""],
    },
    {
      header: "Car",
      items: ["", "", "", ""],
    },
    {
      header: "Pet",
      items: ["", "", "", ""],
    },
  ],
  autoGeneratedState: [
    {
      header: "Career",
      items: ["Doctor", "Teacher", "Athlete", "Actor"],
    },
    {
      header: "Number of Children",
      items: ["0", "1", "2", "3"],
    },
    {
      header: "Car",
      items: ["Tesla", "BMW", "Audi", "Jaguar"],
    },
    {
      header: "Pet",
      items: ["Dog", "Cat", "Fish", "Snake"],
    },
  ],
};

export default categories;
